### PR TITLE
fix error when empty string in path

### LINKED ISSUE #15: `files` input should accept readonly arrays
- While integrating `@gitstart/gitslice-ignore` with an a frontend app using Relay, where the types are generated with `readonly`.
- As a workaround I'm doing `Array.from(files)` to convert the readonly array into a mutable one.
- I believe the `files` input doesn't need to be mutable to use the `gitslice` function.

### LINKED ISSUE #16: Throws `Expected path to be a non-empty string` when an empty string is input to pathsToIgnore or pathsToSlice
image

Reproducing the bug

Add the following test in gitslice/packages/ignore/index.test.ts
```
  it("throws if paths are empty strings", () => {
    expect(
      gitslice({
        mode: "slice",
        pathsToIgnore: [""],
        pathsToSlice: [""],
        files: ["ignore", "ignoreslice"],
      })
    ).toEqual<GitSliceOutput>({
      filesToSlice: [],
      filesToIgnore: ["ignore", "ignoreslice"],
    });
  });
```
Run npm run test

### PR DESCRIPTION
**Pull request by ishmam-mahmud**
- Ignore empty strings in paths inputs
- Accept readonly arrays as input
- Bump version

Resolves #15
Resolves #16

### CODE REVIEW

**Review by richardguerre — APPROVED** [review]

**Comment by richardguerre** [comment]
Maybe also update the README to mention that empty strings are ignored?

File: packages/ignore/index.ts [hunk 1]
```diff
@@ -49,59 +51,44 @@ const parsePath = (path: string, match: boolean) => {
...
 };
 
 export function gitslice(input: GitSliceInput): GitSliceOutput {
-  input.files = input.files.filter((file) => !file.startsWith(".git/"));
-  if (input.mode === "ignore") {
+  const parsedInput = {
+    files: input.files.filter((file) => !file.startsWith(".git/")),
+    mode: input.mode,
+    pathsToIgnore: input.pathsToIgnore.filter((path) => path.length > 0),
+    pathsToSlice: input.pathsToSlice.filter((path) => path.length > 0),
```
Comment (calinanca99) [inline packages/ignore/index.ts:70]: Does this also cover strings that contain whitespace?
